config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#index'

  resources :users
  resources :owners, controller: 'users', type: 'Owner'
  resources :reporters, controller: 'users', type: 'Reporter'
  resources :missings, controller: 'items', type: 'Missing'
  resources :reporteds, controller: 'items', type: 'Reported'
  resources :stops

  get 'lost', to: 'lost#index'
  get 'found', to: 'found#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  scope :reporters, -> { where(type: 'Owner') }
  scope :owners, -> { where(type: 'Reporter') }

  has_many :missing_items, -> { where(type: 'Missing') }, foreign_key:"user_id",
                                                          class_name: "Item"
  has_many :reported_items, -> { where(type: 'Reported') }, foreign_key:"user_id",
                                                            class_name: "Item"
  accepts_nested_attributes_for :missing_items
  accepts_nested_attributes_for :reported_items

  def self.types
    %w(Owner Reporter)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_type
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def show
  end

  def new
    @user = type_class.new

    #TODO: refactor this
    if type == 'Owner'
      @user.missing_items.build
    else
      @user.reported_items.build
    end

    render "new_#{type_class.to_s.downcase}".to_sym
  end

  def create
    @user = User.new(user_params.merge!({type: type_class.to_s}))

    respond_to do |format|
      if @user.save
        format.html { render "thanks_#{type_class.to_s.downcase}".to_sym }
      else
        format.html { render "new_#{type_class.to_s.downcase}".to_sym }
      end
    end
  end

  private

  def set_type
    @type = type
  end

  # Use callbacks to share common setup or constraints between actions.
  def type
    User.types.include?(params[:type]) ? params[:type] : 'User'
  end

  def type_class
    type.constantize
  end

  def set_user
    @user = type_class.find(params[:id])
  end

  def user_params
    params.require(type.underscore.to_sym).permit(:name, :email, :type,
                                missing_items_attributes: [:name, :description, :picture],
                                reported_items_attributes: [:name, :description, :picture]
                                )
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user, html: {class: "form-lost-property"}) do |f| %>

  <% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %>
      prohibited this user from being saved:</h2>

    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <%= f.text_field :name, placeholder: "Your Name", class:"form-control" %>
  <%= f.email_field :email, placeholder: "Your Email", class:"form-control" %>

  <% if @type == "Owner" %>

    <%= f.fields_for :missing_items do |item_field|  %>
      <%= item_field.text_field :name, placeholder: "Brief description of the item", class:"form-control"  %>
      <%= item_field.text_area :description, placeholder: "Detail description", class:"form-control"  %>
      <p>Do you have a photo of the item?</p>
      <%= item_field.file_field :picture %>
    <% end %>

  <% else %>

    <%= f.fields_for :reported_items do |item_field|  %>
      <%= item_field.text_field :name, placeholder: "Brief description of the item", class:"form-control"  %>
      <%= item_field.text_area :description, placeholder: "Detail description", class:"form-control"  %>
      <p>Do you have a photo of the item?</p>
      <%= item_field.file_field :picture %>
    <% end %>

  <% end %>

  <%= f.submit 'Report missing item', class: "btn btn-default"  %>

<% end %>

app/views/users/_info.html.erb
<main class="jumbotron">
  <h1>File a report</h1>
</main>

<h4>PTV Lost Property Enquiries</h4>
<h4>
  <a href="tel:1800 800 007">
    <i class="glyphicon glyphicon-earphone"></i>1800 800 007</a>
</h4>
<p>
  <small>(6am to midnight daily)</small><br/>
  <span class="is_ptv_open"></span>
</p>

<hr/>

<p>
  If an item is located and handed to PTV and/or Victoria Police and matches your report, you will be contacted via the details you have provided.
</p>

app/views/users/_owner_reporting_info.html.erb
<div class="jumbotron">
  <a href="/" class="back-home"><i class="glyphicon glyphicon-chevron-left"></i> HOME </a>
  <h1>Submit report</h1>
</div>

<h4>PTV Lost Property Enquiries</h4>
<h4>
  <a href="tel:1800 800 007"> 
    <i class="glyphicon glyphicon-earphone"></i>&nbsp;1800 800 007</a>
</h4>
<p>
  <small>(6am to midnight daily)</small><br/>
  <span class="is_ptv_open"></span>
</p>

<p class="form-disclaimer">
	If an item is located and handed to PTV and/or Victoria Police and matches your report, you will be contacted via the details you have provided.
</p>

app/views/users/_reporter_reporting_info.html.erb
<div class="jumbotron">
  <a href="/" class="back-home"><i class="glyphicon glyphicon-chevron-left"></i> HOME </a>
  <h1>Found an item ?</h1>
</div>

<h4>Please report to the closest police station or hand it to the tram driver</h4>

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/new_owner.html.erb
<%= render 'owner_reporting_info' %>

<%= render 'form' %>

app/views/users/new_reporter.html.erb
<%= render 'reporter_reporting_info' %>

<%= render 'form' %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Type:</strong>
  <%= @user.type %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/users/thanks.html.erb
<%= render "info" %>

<!--TODO: Add padding  -->
<div class="bg-success">
  <p>Your report has been submitted. Good Luck!</p>
</div>

app/views/users/thanks_owner.html.erb
<!--TODO: Add padding  -->
<div class="bg-success">
  <a href="/" class="back-home"><i class="glyphicon glyphicon-chevron-left"></i> BACK TO HOME </a>
  <h4>Your report has been submitted. Good luck!</h4>
</div>

<div class="logo-container">
  <small>Crowdsource lost & found on PTV (beta)</small>
  <img src="<%= asset_path "logo-650x150.png" %>" alt="LOST+FOUND" width="240"/>
</div>


<p>
  <%= link_to "Lost an item?", lost_path, class: "btn btn-large btn-lost" %>
</p>
<p>
  <%= link_to "Found an item?", found_path, class: "btn btn-large btn-found" %>
</p>

app/views/users/thanks_reporter.html.erb
<!--TODO: Add padding  -->
<div class="bg-success">
  <a href="/" class="back-home"><i class="glyphicon glyphicon-chevron-left"></i> BACK TO HOME </a>
  <p>Your report has been submitted. Thank you!</p>
</div>

<div class="logo-container">
  <small>Crowdsource lost & found on PTV (beta)</small>
  <img src="<%= asset_path "logo-650x150.png" %>" alt="LOST+FOUND" width="240"/>
</div>


<p>
  <%= link_to "Lost an item?", lost_path, class: "btn btn-large btn-lost" %>
</p>
<p>
  <%= link_to "Found an item?", found_path, class: "btn btn-large btn-found" %>
</p>