config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#index'

  resources :users
  resources :owners, controller: 'users', type: 'Owner'
  resources :reporters, controller: 'users', type: 'Reporter'
  resources :missings, controller: 'items', type: 'Missing'
  resources :reporteds, controller: 'items', type: 'Reported'
  resources :stops

  get 'lost', to: 'lost#index'
  get 'found', to: 'found#index'
end

app/models/stop.rb
class Stop < ActiveRecord::Base

  # TODO: Change this to Active model. We don't store stop data in the database
  TRAM = 1
  ALL = 0
  PAGINATE = 3

  def self.tram_stops_by_lat_lng(lat, lng)
    all_stops_by_lat_lng(lat, lng).select { |k,v| k['result']['transport_type'] == 'tram'}.take(PAGINATE)
  end

  def self.tram_stops_by_addr(addr)
    all_stops_by_addr(addr).select { |k,v| k['result']['transport_type'] == 'tram'}.take(PAGINATE)
  end

  private

  def self.api
    # TODO: Move api key to ENV specific file
    @api ||= PtvTimetable::API.new('1000491', '6958c2fa-05c9-11e5-9cc2-02f9e320053a')
  end

  def self.all_tram_lines(stop_id)
    api.broad_next_departures(Stop::TRAM, stop_id, Stop::ALL)
  end

  def self.all_stops_by_lat_lng(lat, lng)
    lat1, lng1 = Geocoder.coordinates("100 Swanston street, Melbourne")
    api.near_me(lat1,lng1)
  end

  def self.all_stops_by_addr(address)
    lat1, lng1 = Geocoder.coordinates(address)
    api.near_me(lat1,lng1)
  end

  def self.uniq_tram_lines(data)
    stop_id = stop_id(data)
    all_tram_lines(stop_id)['values'].uniq { |line| line_id(line) }
  end

  def self.result(data)
    data['result']
  end

  def self.stop_name(data)
    location_name = result(data)['location_name']
    stop_no =  %q(<label class="label-info label pull-right">) + "Stop " + location_name.split('#').second + "</label>"
    stop_name = location_name.split('#').first
    stop_name + stop_no
  end

  def self.stop_id(data)
    result(data)['stop_id']
  end

  def self.platform(data)
    data['platform']
  end

  def self.direction(data)
    platform(data)['direction']
  end

  def self.direction_name(data)
    direction(data)['direction_name']
  end

  def self.line(data)
    direction(data)['line']
  end

  def self.line_number(data)
    line(data)['line_number']
  end

  def self.line_id(data)
    line(data)['line_id']
  end

  def self.info(data)
    line_number(data) + ' to ' + direction_name(data)
  end
end

app/controllers/stops_controller.rb
class StopsController < ApplicationController
  before_action :set_stop, only: [:show, :edit, :update, :destroy]

  # GET /stops
  # GET /stops.json
  def index
    if params[:address].present?
      @tram_stops = Stop.tram_stops_by_addr(params[:address])
    else
      @tram_stops = Stop.tram_stops_by_lat_lng(params[:lat], params[:lng])
    end
  end

  # GET /stops/1
  # GET /stops/1.json
  def show
  end

  # GET /stops/new
  def new
    @stop = Stop.new
  end

  # GET /stops/1/edit
  def edit
  end

  # POST /stops
  # POST /stops.json
  def create
    @stop = Stop.new(stop_params)

    respond_to do |format|
      if @stop.save
        format.html { redirect_to @stop, notice: 'Stop was successfully created.' }
        format.json { render :show, status: :created, location: @stop }
      else
        format.html { render :new }
        format.json { render json: @stop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stops/1
  # PATCH/PUT /stops/1.json
  def update
    respond_to do |format|
      if @stop.update(stop_params)
        format.html { redirect_to @stop, notice: 'Stop was successfully updated.' }
        format.json { render :show, status: :ok, location: @stop }
      else
        format.html { render :edit }
        format.json { render json: @stop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stops/1
  # DELETE /stops/1.json
  def destroy
    @stop.destroy
    respond_to do |format|
      format.html { redirect_to stops_url, notice: 'Stop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stop
      @stop = Stop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stop_params
      params[:stop]
    end
end

app/helpers/stops_helper.rb
module StopsHelper
end

app/views/stops/_form.html.erb
<%= form_for(@stop) do |f| %>
  <% if @stop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stop.errors.count, "error") %> prohibited this stop from being saved:</h2>

      <ul>
      <% @stop.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stops/edit.html.erb
<h1>Editing Stop</h1>

<%= render 'form' %>

<%= link_to 'Show', @stop %> |
<%= link_to 'Back', stops_path %>

app/views/stops/index.html.erb
<div class="jumbotron">
  <a href="/" class="back-home"><i class="glyphicon glyphicon-chevron-left"></i> HOME </a>
  <h1>Which tram?</h1>
</div>

<div>
  <p>Tell us where you got off<br/>
  someone might have found your item</p>
</div>

<div class="transport">
 <% @tram_stops.each do |stop| %>
    <div class="tram-stop">
      <h4><%= raw(Stop.stop_name(stop)) %></h4>
      <% if Rails.env == "development" %>
<!--         <h3 style="color:blue"><%= stop['result']['transport_type'] %></h3>
        <h3 style="color:red"><%= stop['result']['stop_id'] %></h3> -->
      <% end %>
      <% Stop.uniq_tram_lines(stop).each do |line| %>
        <%= button_tag "Tram " + Stop.info(line), class: 'tram-line btn btn-large' %>
        <div class="last-five-trams">
          <p><b>How long ago did you get off?</b></p>
          <ul class="list-group">
            <li><%= link_to "10 minutes", reporteds_path %></li>
            <li><%= link_to "30 minutes", reporteds_path %></li>
            <li><%= link_to "1 hours", reporteds_path %></li>
            <li class="earlier"><%= link_to "I got of earlier...", reporteds_path %></li>
          </ul>
          </div>
      <% end %>
    </div>
  <% end %>
  <br>
  <small>Can't find your tram? Try expanding or refining your search</small>
  <div class="refine-location input-group">
    <input type="text" class="location-address form-control" placeholder="Enter location">
    <span class="input-group-btn">
      <button class="location-btn-found btn btn-default" type="button">Search</button>
    </span>
  </div>
</div>

app/views/stops/new.html.erb
<h1>New Stop</h1>

<%= render 'form' %>

<%= link_to 'Back', stops_path %>

app/views/stops/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_stop_path(@stop) %> |
<%= link_to 'Back', stops_path %>