config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#index'

  resources :users
  resources :owners, controller: 'users', type: 'Owner'
  resources :reporters, controller: 'users', type: 'Reporter'
  resources :missings, controller: 'items', type: 'Missing'
  resources :reporteds, controller: 'items', type: 'Reported'
  resources :stops

  get 'lost', to: 'lost#index'
  get 'found', to: 'found#index'
end

app/models/item.rb
class Item < ActiveRecord::Base
  scope :missing, -> { where(type: 'Missing') }
  scope :reported, -> { where(type: 'Reported') }
  #TODO: We can't just return all items
  scope :recent, -> { order(created_at: :desc) }

  belongs_to :user
  # This method associates the attribute ":avatar" with a file attachment
  has_attached_file :picture, styles: {
    thumb: '100x100>',
    square: '200x200#',
    medium: '300x300>'
  }

  # Validate the attached image is image/jpg, image/png, etc
  validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/

  # before_save :default_values

  def self.types
    %w(Missing Reported)
  end

  # def default_values
    # self.thumbnail ||= 'https://raw.githubusercontent.com/Boo-Hiss/lost-found/master/app/assets/images/floral-wallet-red.jpeg'
  # end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_type
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = type_class.all
    render type_class.to_s.downcase.to_sym
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_type
    @type = type
  end

  def type
    Item.types.include?(params[:type]) ? params[:type] : 'Item'
  end

  def type_class
    type.constantize
  end

  def set_item
    @item = type_class.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def item_params
    params.require(:item).permit(:name, :description, :status)
  end
end

app/helpers/items_helper.rb
module ItemsHelper# helpers/animals_helper.rb
  def sti_type_path(type = "item", item = nil, action = nil)
    send "#{format_sti(action, type, type)}_path", item
  end

  def format_sti(action, type, item)
    action || item ? "#{format_action(action)}#{type.underscore}" : "#{type.underscore.pluralize}"
  end

  def format_action(action)
    action ? "#{action}_" : ""
  end
end

app/views/items/_form.html.erb
<% form_for(@item, html: {class: "form-lost-property"}) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= fields_for :user do |user_field|  %>
    <%= user_field.text_field :name, placeholder: "Your Name", class:"form-control" %>
    <%= user_field.email_field :email, placeholder: "Your Email", class:"form-control" %>
  <% end %>
  <%= f.text_field :name, placeholder: "Brief description of the item", class:"form-control"  %>
  <%= f.text_area :description, placeholder: "Detail description", class:"form-control"  %>

  <p>Do you have a photo of the item?</p>

  <%= f.submit %>

<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/missing.html.erb
<div class="jumbotron">
  <a href="/" class="back-home"><i class="glyphicon glyphicon-chevron-left"></i> HOME </a>
  <h1>Missing</h1>
</div>

<div class="item-list">
<% @items.each do |item| %>
  <div class="item">
    <h4><%= item.name %></h4>
    <p><%= item.description %></p>
    <% if item.thumbnail.nil? %>
      <%= image_tag item.picture.url(:thumb) %>
    <% else %>
      <%= image_tag item.thumbnail %>
    <% end %>
    <button class="btn btn-large btn-found update-the-owner">Update the owner</button>
    <div class="update-owner-message">
      <textarea class="form-control" rows="3" placeholder="When and where the item was handed in?" ></textarea>
      <button class="btn btn-large btn-found pull-right submit" width="100">Submit</button>
    </div>

  </div>
<% end %>
</div>

<div class="add-lost-item">
	<p>If you cannot find a matching item,<br/>please add a description of your finding</p>
	<%= link_to "ADD A NEW ITEM", new_reporter_path, class: "btn btn-lost" %>
</div>



<style>
.update-owner-message {
  padding: 1em;
  background-color: rgba(242,200,75,0.5);
  height: 0;
  opacity: 0;
  overflow: hidden;
  transition: all 0.3s ease-in;
 }

.update-owner-message.shown {
  height: 150px;
  opacity: 1;
  transition: all 0.5s ease-in;
}

.item {
  transition: all 0.5s ease-in;
}

.item.fade {
  opacity: 0;
  transition: all 0.5s ease-in;
}

.update-owner-message .submit {
	width: 100px !important;
	margin-top: 0.5em;
 }
</style>

<script>

$(".update-the-owner").click(function() {
	$(this).next().addClass("shown");
});

$(".submit").click(function() {
	$(this).parent().prev().removeClass("update-the-owner");
	$(this).parent().prev().text("Item status updated ✓");
	$(this).parent().removeClass("shown");
	$(this).closest(".item").slideUp(1000).fadeOut(1000);
	// $(this).closest(".item").addClass("fade").delay(800).css("display","none");
});

</script>

app/views/items/new.html.erb
<!-- <h1>New Item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %> -->

<main class="jumbotron">
  <h1>File a report</h1>
</main>

<h4>PTV Lost Property Enquiries</h4>
<h4>
  <a href="tel:1800 800 007">
    <i class="glyphicon glyphicon-earphone"></i>1800 800 007</a>
</h4>
<p>
  <small>(6am to midnight daily)</small><br>
  <span class="is_ptv_open">
    <span class="label label-success">PTV is open now</span>
  </span>
</p>

<hr>

<p>
  If an item is located and handed to PTV and/or Victoria Police and matches your report, you will be contacted via the details you have provided.
</p>

<form class="form-lost-property">
  <input class="form-control" placeholder="Name" type="text">
  <input class="form-control" placeholder="Email" type="email">
  <input class="form-control" placeholder="Item Name" type="name">
  <textarea class="form-control" placeholder="Item Description" rows="3"></textarea>
  <p>Do you have a photo of the item?</p>
  <input accept="image/*" capture="camera" class="image-upload" id="capture" type="file">
  <button class="btn btn-primary" type="submit">Submit report</button>
</form>

<hr>

app/views/items/reported.html.erb
<div class="jumbotron">
  <a href="/" class="back-home"><i class="glyphicon glyphicon-chevron-left"></i> HOME </a>
  <h1>Recently Found</h1>
</div>

<div class="item-list">
<% @items.each do |item| %>
  <div class="item">
    <h4><%= item.name %></h4>
    <p><%= item.description %></p>
    <!-- <%= image_tag item.picture.url(:thumb) %> -->
    <%= image_tag item.thumbnail %>
  </div>
<% end %>
</div>

<div class="add-lost-item">
	<p>Can't find your item?<br/>Give us a description of your item</p>
  <%= link_to "ADD A LOST ITEM", new_owner_path, class: "btn btn-lost" %>
</div>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>Status:</strong>
  <%= @item.status %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>